-- SI EXISTE EL ESQUEMA, SE ELIMINA
DROP SCHEMA IF EXISTS NEGOCIO_PESCA;

-- SI NO EXISTE, SE CREA EL ESQUEMA
CREATE SCHEMA IF NOT EXISTS NEGOCIO_PESCA;

-- UTILIZACIÓN DEL SCHEMA NEGOCIO_PESCA
USE NEGOCIO_PESCA;

-- CREACIÓN DE TABLAS
CREATE TABLE IF NOT EXISTS EMPLEADOS(
	ID_EMPLEADO INT 				NOT NULL AUTO_INCREMENT,
	NOMBRE_APELLIDO VARCHAR(50) 	NOT NULL,
	DIRECCION VARCHAR(250),
    TELEFONO VARCHAR(20) 					NOT NULL,
    CORREO_ELECTRONICO VARCHAR(100),
    PRIMARY KEY (ID_EMPLEADO)
);

CREATE TABLE IF NOT EXISTS VENTAS(
	ID_VENTA INT 					NOT NULL AUTO_INCREMENT,
	FECHA DATE 						NOT NULL,
	HORA TIME 						NOT NULL,
	ID_EMPLEADO INT					NOT NULL,
	PRIMARY KEY(ID_VENTA),
	FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO)
);

CREATE TABLE IF NOT EXISTS PROVEEDORES(
	ID_PROVEEDOR INT 				NOT NULL AUTO_INCREMENT,
    NOMBRE_APELLIDO VARCHAR(100) 	NOT NULL,
    DIRECCION VARCHAR(250),
    TELEFONO VARCHAR(20) 			NOT NULL,
    CORREO_ELECTRONICO VARCHAR(100),
    URL_LISTA_PRECIOS VARCHAR(80),
    PRIMARY KEY(ID_PROVEEDOR)
);

CREATE TABLE IF NOT EXISTS CATEGORIAS(
	ID_CATEGORIA INT 				NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) 				NOT NULL,
    PRIMARY KEY(ID_CATEGORIA)
);

CREATE TABLE IF NOT EXISTS SUBCATEGORIAS(
	ID_SUBCATEGORIA INT 			NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) 				NOT NULL,
    ID_CATEGORIA INT				NOT NULL,
    PRIMARY KEY(ID_SUBCATEGORIA),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE IF NOT EXISTS PRODUCTOS(
	ID_PRODUCTO INT 				NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(70) 				NOT NULL,
    DESCRIPCION VARCHAR(250),
    PRECIO_COSTO DECIMAL(8,2) 		NOT NULL,
    PRECIO_LISTA DECIMAL(8,2) 		NOT NULL,
    PRECIO_FINAL DECIMAL(8,2) 		NOT NULL,
    CANTIDAD_DISPONIBLE INT 		NOT NULL,
    ID_SUBCATEGORIA INT				NOT NULL,
    PRIMARY KEY (ID_PRODUCTO),
    FOREIGN KEY (ID_SUBCATEGORIA) REFERENCES SUBCATEGORIAS(ID_SUBCATEGORIA)
);

CREATE TABLE IF NOT EXISTS METODOS_PAGO(
	ID_METODO_PAGO INT 				NOT NULL AUTO_INCREMENT,
    NOMBRE VARCHAR(50) 				NOT NULL,
    PRIMARY KEY(ID_METODO_PAGO)
);

CREATE TABLE IF NOT EXISTS DETALLE_VENTA(
	ID_DETALLE_VENTA INT 			NOT NULL AUTO_INCREMENT,
    ID_VENTA INT					NOT NULL,
    ID_PRODUCTO INT					NOT NULL,
    CANTIDAD INT 					NOT NULL,
    PRECIO_UNITARIO DECIMAL(8,2) 	NOT NULL,
    PRIMARY KEY (ID_DETALLE_VENTA),
    FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO)
);

CREATE TABLE IF NOT EXISTS PRODUCTO_PROVEEDOR(
	ID_PRODUCTO_PROVEEDOR INT 		NOT NULL AUTO_INCREMENT,
    ID_PRODUCTO INT					NOT NULL,
    ID_PROVEEDOR INT				NOT NULL,
    PRECIO_COMPRA DECIMAL(8,2) 		NOT NULL,
    PRIMARY KEY (ID_PRODUCTO_PROVEEDOR),
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO),
    FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR)
);

CREATE TABLE IF NOT EXISTS DETALLE_METODO_PAGO_VENTA(
	ID_DETALLE_METODO_PAGO_VENTA INT NOT NULL AUTO_INCREMENT,
    ID_VENTA INT					NOT NULL,
    ID_METODO_PAGO INT				NOT NULL,
    MONTO_PAGADO DECIMAL(9,2) 		NOT NULL,
    PRIMARY KEY (ID_DETALLE_METODO_PAGO_VENTA),
    FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA),
    FOREIGN KEY (ID_METODO_PAGO) REFERENCES METODOS_PAGO(ID_METODO_PAGO)
);