USE negocio_pesca;

-- SELECT * FROM DETALLE_METODO_PAGO_VENTA ;

START TRANSACTION;

DELETE FROM DETALLE_METODO_PAGO_VENTA WHERE ID_DETALLE_METODO_PAGO_VENTA=1;

DELETE FROM DETALLE_METODO_PAGO_VENTA WHERE ID_DETALLE_METODO_PAGO_VENTA=2;

DELETE FROM DETALLE_METODO_PAGO_VENTA WHERE ID_DETALLE_METODO_PAGO_VENTA=3;

-- SELECT * FROM DETALLE_METODO_PAGO_VENTA WHERE ID_DETALLE_METODO_PAGO_VENTA=2;
-- ROLLBACK;
-- SELECT * FROM DETALLE_METODO_PAGO_VENTA WHERE ID_DETALLE_METODO_PAGO_VENTA=2;

COMMIT;