USE negocio_pesca;

-- SELECT * FROM DETALLE_METODO_PAGO_VENTA ;

SET @@autocommit = 0;

START TRANSACTION;

DELETE FROM DETALLE_METODO_PAGO_VENTA WHERE ID_DETALLE_METODO_PAGO_VENTA=1;

DELETE FROM DETALLE_METODO_PAGO_VENTA WHERE ID_DETALLE_METODO_PAGO_VENTA=2;

DELETE FROM DETALLE_METODO_PAGO_VENTA WHERE ID_DETALLE_METODO_PAGO_VENTA=3;

-- SELECT * FROM DETALLE_METODO_PAGO_VENTA WHERE ID_DETALLE_METODO_PAGO_VENTA=2;
-- ROLLBACK;
-- SELECT * FROM DETALLE_METODO_PAGO_VENTA WHERE ID_DETALLE_METODO_PAGO_VENTA=2;

COMMIT;

-- SELECT * FROM PRODUCTO_PROVEEDOR;

START TRANSACTION;

INSERT INTO PRODUCTO_PROVEEDOR (ID_PRODUCTO, ID_PROVEEDOR, PRECIO_COMPRA) VALUES (5, 10, 14.99);
INSERT INTO PRODUCTO_PROVEEDOR (ID_PRODUCTO, ID_PROVEEDOR, PRECIO_COMPRA) VALUES (8, 13, 34.99);
INSERT INTO PRODUCTO_PROVEEDOR (ID_PRODUCTO, ID_PROVEEDOR, PRECIO_COMPRA) VALUES (2, 4, 24.99);
INSERT INTO PRODUCTO_PROVEEDOR (ID_PRODUCTO, ID_PROVEEDOR, PRECIO_COMPRA) VALUES (4, 2, 64.99);
SAVEPOINT SP_1;

INSERT INTO PRODUCTO_PROVEEDOR (ID_PRODUCTO, ID_PROVEEDOR, PRECIO_COMPRA) VALUES (5, 7, 24.99);
INSERT INTO PRODUCTO_PROVEEDOR (ID_PRODUCTO, ID_PROVEEDOR, PRECIO_COMPRA) VALUES (5, 5, 74.99);
INSERT INTO PRODUCTO_PROVEEDOR (ID_PRODUCTO, ID_PROVEEDOR, PRECIO_COMPRA) VALUES (8, 6, 84.99);
INSERT INTO PRODUCTO_PROVEEDOR (ID_PRODUCTO, ID_PROVEEDOR, PRECIO_COMPRA) VALUES (10, 9, 4.99);
SAVEPOINT SP_2;

-- RELEASE SAVEPOINT SP_1;

COMMIT;
